service: backlog2slack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  backlog2slack:
    handler: index.handler
    description: "backlog to slack"
    memorySize: 128
    timeout: 10
    events:
      - http:
          path: backlog2slack/{room}
          method: post
    environment:
      WEBHOOKURI: https://hooks.slack.com/services/xxxxx
      BASEURL: https://xxxxx.backlog.jp/
      BOTNAME: backlogbot
